// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var app;
    app = angular.module('app', []);
    Mock.mockjax(app);
    return app.controller('appCtrl', function($scope, $http) {
      var box;
      box = $scope.box = [];
      $scope.get = function() {
        return $http({
          url: 'http://g.cn'
        }).success(function(data) {
          return box.push(data);
        });
      };
      return $scope.get();
    });
  })();

}).call(this);
