// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    return Mock.mockjax = function(module) {
      var Item, error;
      Item = (function() {
        function Item() {}

        Item.prototype.add = function(url) {
          var k, v, _ref;
          _ref = Mock._mocked;
          for (k in _ref) {
            v = _ref[k];
            if (k === url) {
              return this[url] = Mock.mock(v.template);
            }
          }
        };

        return Item;

      })();
      try {
        return module.config(function($httpProvider) {
          var item;
          item = new Item();
          return $httpProvider.interceptors.push(function() {
            return {
              request: function(config) {
                item.add(config.url);
                if (item[config.url]) {
                  config.url = "?mockUrl=" + config.url;
                }
                return config;
              },
              response: function(response) {
                var url;
                url = response.config.url.substr(9);
                if (item[url]) {
                  response.data = item[url];
                }
                return response;
              }
            };
          });
        });
      } catch (_error) {
        error = _error;
        return console.error('生成mock.angular失败，例：var app = angular.module("app", []); Mock.mockjax(app);');
      }
    };
  })();

}).call(this);

//# sourceMappingURL=mock.angular.map
